//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkinsoftVmodulu.UI.BackOffice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.44.254,1433;Initial Catalog=WOLVOX8_001_2021_WOLVOX;Persist S" +
            "ecurity Info=True;User ID=sa;Password=Abc123+-*q1")]
        public string D__AKINSOFT_WOLVOX8_001_2020_WOLVOXConnectionString {
            get {
                return ((string)(this["D__AKINSOFT_WOLVOX8_001_2020_WOLVOXConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.44.254,1433;Initial Catalog=WOLVOX8_DOSYA;User ID=sa;Password" +
            "=Abc123+-*q1")]
        public string D__AKINSOFT_WOLVOX8_DOSYAConnectionString {
            get {
                return ((string)(this["D__AKINSOFT_WOLVOX8_DOSYAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.44.254,1433;Initial Catalog=WOLVOX8_001_2021_WOLVOX;Persist S" +
            "ecurity Info=True;User ID=sa;Password=Abc123+-*q1")]
        public string D__AKINSOFT_WOLVOX8_001_2020_WOLVOXConnectionString1 {
            get {
                return ((string)(this["D__AKINSOFT_WOLVOX8_001_2020_WOLVOXConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.44.254,1433;Initial Catalog=WOLVOX8_SIRKET;User ID=sa;Passwor" +
            "d=Abc123+-*q1")]
        public string D__AKINSOFT_WOLVOX8_SIRKETConnectionString {
            get {
                return ((string)(this["D__AKINSOFT_WOLVOX8_SIRKETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.44.254;Initial Catalog=WOLVOX8_SIRKET;User ID=sa;Password=Abc" +
            "123+-*q1")]
        public string WOLVOX8_SIRKETConnectionString {
            get {
                return ((string)(this["WOLVOX8_SIRKETConnectionString"]));
            }
        }
    }
}
