<?xml version="1.0" encoding="utf-8"?><Database Name="WOLVOX8_001_2021_WOLVOX" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.44.254,1433;Initial Catalog=WOLVOX8_001_2021_WOLVOX;Persist Security Info=True;User ID=sa" SettingsObjectName="AkinsoftVmodulu.UI.BackOffice.Properties.Settings" SettingsPropertyName="D__AKINSOFT_WOLVOX8_001_2020_WOLVOXConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FATURA" Member="FATURA">
    <Type Name="FATURA">
      <Column Name="BLKODU" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FATURA_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BLCRKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CARIKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TICARI_UNVANI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ADI_SOYADI" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="VERGI_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VERGI_DAIRESI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TEL1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FAKS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ADRESI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ILI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="OZEL_KODU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KUL_STOK_FIYATI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FATURA_NO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TARIHI" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VADESI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GRUBU" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="KDV_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KDV_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EKBILGI_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EKBILGI_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OTV_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_KUL_CARI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_ORAN_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_ORAN_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_ORAN_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_ORAN_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_STOK" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_OZEL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_TUTAR_OZEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_KUL_ALT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK_ORAN_ALT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_ALT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_ALT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CARIHRK_ISLE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="STOKHRK_ISLE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DOVIZ_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DOVIZ_BIRIMI" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="KPBDVZ_CARI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DVZ_HSISLE_STOK" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DVZ_HSISLE_CARI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAZ_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAZ_PERSONEL" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAZ_PERS_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SEVK_ADRESI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SEVK_ILI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SEVK_ILCESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="TOPLAM_ALT_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ARA_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YUVARLAMA_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_KDV_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_OTV_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_GENEL_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTAR1_TOPLAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTAR2_TOPLAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ALT_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ARA_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YUVARLAMA_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_KDV_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_OTV_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_GENEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FATURA_KESILDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_FAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_YUZDESI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DEGISTIRME_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KAYDEDEN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DEGISTIREN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VADE_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ORTALAMA_VADE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IPTAL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SILINDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HESAPLANAN_KDV_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HESAPLANAN_KDV_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEVKIFAT_ORANI_1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TEVKIFAT_ORANI_2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TEVKIFAT_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEVKIFAT_TUTARI_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FATURA_TIPI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="GM_ENTEGRASYON" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TOPLAM_OIV_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_OIV_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OIV_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ACIKLAMA_2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BLFIRSATKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SUBE_KODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IHRAC_KAYDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OTEL_ENTEGRASYON" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ULKESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SEVK_ULKESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="YDF_BLBNHSKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="YDF_KPB_EKUC_SIGORTA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_KPB_EKUC_NAVLUN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_KPB_EKUC_GUMRUK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_DVZ_EKUC_SIGORTA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_DVZ_EKUC_NAVLUN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_DVZ_EKUC_GUMRUK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YDF_TUTAR_TIPI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YDF_TUTAR_TIPI_ACIKLAMA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ADRESI_FATURA" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ILI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ULKESI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_OZEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_ALT1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_ALT2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_ISK_FAT_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EFATURA_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_DURUM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_GUID" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="EFATURA_FATURANO" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="TOPLAM_KDV_85_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_KDV_85_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV85_MATRAHI_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TARIHI2" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EK_MALIYET_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CARIHRKISLE_DISABLED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="STOKHRKISLE_DISABLED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KPB_EKKESINTILER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_EKKESINTILER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BONUS_ISLE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OFFLINE_DURUM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OFFLINE_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BLKAMPANYAKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SOURCE_APP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FATURA_SERI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GM_GGB_TESCIL_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GM_FAT_IND_DONEMI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="GM_ARACI_VRTC" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="YUVARLAMA_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CEP_TEL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KAYIT_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EFATURA_ACIKLAMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EFATURA_GOND_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EFATURA_GIB_DURUM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_SENARYO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KARGO_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EDF_BELGE_TURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EDF_BELGE_TURU_DIG" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="YEVMIYE_BELGETURU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="KARGO_FIRMASI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SEVK_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SEVK_TANIMI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEVK_YETKILISI" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="SEVK_TEL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ISK_TUTAR_PRM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_PRM_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EFATURA_HESAP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_GONDTIPI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_TURU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_TIPI" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EFATURA_SABLONKODU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BONUS_ODEME_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EFATURA_ETICARET" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_ODEME_TURU" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="EFATURA_ODEME_TURU_DIGER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EFATURA_SITE_ADI" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EFATURA_TFIRMA_VKN" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EFATURA_TFIRMA_ADI" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="EFATURA_MAILGOND" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OFFLINE_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EFATURA_ARACI_FIRMA" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="EFATURA_MAPCODE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BLITHALATKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EFATURA_POSTA_KUTUSU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EFATURA_PASAPORT_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EFATURA_PASAPORT_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EFATURA_UYRUK" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="EFATURA_ARCKRM_VERGINO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EFATURA_ARCKRM_UNVANI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FATURA_NO_ERP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_SGK_FATURA_TIPI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EFATURA_SGK_MKL_KODU" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EFATURA_SGK_MKL_ADI" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EFATURA_SGK_DOSYA_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EFATURA_SGK_DONEM_BSL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EFATURA_SGK_DONEM_BTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KARGO_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TEVKIFAT_LIMIT_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EK_MALIYET_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EFATURA_BEDELSIZ" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="VIRMAN_BLCRKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TOPLAM_OTEL_KNKVR_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAM_OTEL_KNKVR_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BLSAYACKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="OTO_EFATURA_GONDERIMI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OTO_GONDERIM_HATA" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="OZELALANTANIM_6" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_HBIRIMI_VERGINO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OZELALANTANIM_13" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OZELALANTANIM_14" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OZELALANTANIM_15" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CARI" Member="CARI">
    <Type Name="CARI">
      <Column Name="BLKODU" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CARIKODU" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GRUBU" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="ARA_GRUBU" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="ALT_GRUBU" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="OZEL_KODU1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OZEL_KODU2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OZEL_KODU3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KAYIT_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ADI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SOYADI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TICARI_UNVANI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="VERGI_DAIRESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="VERGI_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ISKONTO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISKONTO_ORAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEL1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TEL2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EV_TEL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CEP_TEL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FAKS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ICQ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="WEB" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOVIZ_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DOVIZ_BIRIMI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="KREDI_LIMIT_UYARI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KREDI_LIMITI_CEKSENET" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VADE_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VADE_GUN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VADE_AY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VADE_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZARLAMA_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAZARLAMA_ORAN_URUN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZARLAMA_ORAN_ISCILIK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MUHKODU_ALIS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MUHKODU_SATIS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ADRESI_1" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ILI_1" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI_1" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="KEFIL_ADISOYADI" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="KEFIL_TEL1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KEFIL_TEL2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KEFIL_ADRES" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ADRESI_2" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ILI_2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI_2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="STOK_FIYATI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YASLANDIRMA_GRUBU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RISKLI_MUSTERI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RISK_NOTU" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="K_KARTI1" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="K_KARTI2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BABA_ADI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ANA_ADI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DOGUM_YERI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DOGUM_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TC_KIMLIK_NO" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="HUVIYET_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HUVIYET_TURU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MEDENI_HALI" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DINI" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ILI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SERI_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CILTNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AILE_SIRA_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SIRA_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NUFUS_DAIRESI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VERILIS_NEDENI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UYRUGU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MAHKOY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CINSIYETI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KAYDEDEN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DEGISTIREN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DEGISTIRME_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SILINDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BANKA_ADI_1" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_HESNO_1" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_ADI_2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_HESNO_2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="NOT_1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="NOT_2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="NOT_3" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="GARSON" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PDASIFRE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BONUS_TANIMI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OZEL_TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WEB_USER_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WEB_USER_PASSW" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="PDA_ENTEGRASYON" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AKTIF" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAZ_BLCRKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SERVIS_PERSONELI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="POTANSIYELMUSTERIDURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEKTOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="POTANSIYELMUSTERIKAYNAGI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YILLIKKAZANC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CALISANSAYISI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RATING" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BLKAMPANYAKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TOPLAMALISVERIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOPLAMPUAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROTAKODU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SUBE_KODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ULKESI_1" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ULKESI_2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_1_SUBE_ADI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_1_SUBE_KODU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BANKA_1_IBAN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BANKA_1_SWIFT" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_2_SUBE_ADI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BANKA_2_SUBE_KODU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BANKA_2_IBAN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BANKA_2_SWIFT" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ISK1_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK1_ORAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK2_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK2_ORAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK3_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISK3_ORAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ADRESI_FATURA" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ILI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ILCESI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ULKESI_FATURA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="USTPAZ_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="USTPAZ_BAGTARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KAN_GRUBU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EFATURA_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZP_UYE_PRIMI_VERILDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ROTA_GRUBU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ROTA_SIRASI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OFFLINE_DURUM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OFFLINEBLCRKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="KAREKOD_TRSALAN" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ALICI_GRUBU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SOURCE_APP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EFATURA_SENARYO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KONUM1_LAT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KONUM1_LNG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UYARI_METNI" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_CADDE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_KOY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_BINAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_DISNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_ICNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_PKODU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_ID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TAKSITLI_MUSTERI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ROTA_ARALIK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAZARLAMACI_USER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KEFIL_TCNO" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_MAHALLE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_ADR_BLOKADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_GONDTIPI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EFATURA_HESAP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OFFLINE_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="RAPOR_RENGI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EFATURA_POSTA_KUTUSU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EFATURA_GERCEK_KISI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AFT_EK_KESINTI_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ADI_SOYADI" Type="System.String" DbType="VarChar(101)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PAZ_HEDEF_TIPI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EIRSALIYE_POSTA_KUTUSU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EIRSALIYE_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EMUSTAHSIL_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KAMU_KURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PASIFLIK_TARIHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FATURAHR" Member="FATURAHR">
    <Type Name="FATURAHR">
      <Column Name="BLKODU" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BLFTKODU" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BLSTKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STOKKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="STOK_ADI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BIRIMI" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="BIRIMI_2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MIKTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTARI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_FIYATI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_KDV_HARICFY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_IND_FIYAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_ARA_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_IND_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_FIYATI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_KDV_HARICFY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_IND_FIYAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_ARA_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_IND_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOVIZ_BIRIMI" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BIRIM_CARPANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_OZEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_OZEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ARATUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OTV_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OTV_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OTVLI_TOPLAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_TOPLAM_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_KDVLI_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_TOPLAM_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_KDVLI_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DEPO_ADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MUH_KODU_GENEL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OZEL_KODU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EKBILGI_1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_4" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_PERSONEL" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAZ_PERS_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BARKODU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VADE_GUNU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OTV_BIRIMI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OIV_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OIV_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BLHZMKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BIRIMLER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="KPBDVZ" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ANA_STOKKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KPB_FIYATI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_CARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_3_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_OZEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_OZEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SIPTESLIM2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ASORTI_HRK" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ASORTI_MIKTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SIRA_NO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OTV_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OTVLI_TOPLAM_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OTV_BIRIMI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OIV_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEVKIFAT_ORANI_1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TEVKIFAT_ORANI_2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EVRAK_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DOVIZ_ALIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOVIZ_SATIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_85_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAZ_URUN_BF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EK_MALIYET_KPB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SERINO_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BONUS_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BONUS_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BONUS_BRFYT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STOK_ADI_YD" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MASRAF_MERKEZI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DVZ_FIYATI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_PRM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_PRM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_PRM_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_PRM_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEVKIFAT_KODU" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ISTISNA_KODU" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ISK_TUTAR_BONUS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_BONUS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_BONUS_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_BONUS_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OFFLINE_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EFATURA_TESLIM_SARTI" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="EFATURA_TESLIM_ULKE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_TESLIM_IL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_TESLIM_ILCE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EFATURA_TASIMA_KAP_CINSI" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="EFATURA_TASIMA_KAP_NOSU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EFATURA_TASIMA_KAP_ADEDI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EFATURA_TASIMA_SEKLI" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="BLITHALATKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GENEL_BLOB" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DEPOZITO_BLSTKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DEPOZITO_BLMASTERKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="KAYNAKFH_BLKODU" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="EK_MALIYET_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BLPAKETKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ONAYLAMA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SIPARISHR" Member="SIPARISHR">
    <Type Name="SIPARISHR">
      <Column Name="BLKODU" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BLMASKODU" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BLSTKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STOKKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="STOK_ADI" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BIRIMI" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="BIRIMI_2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MIKTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTARI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_FIYATI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_KDV_HARICFY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_IND_FIYAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_ARA_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_IND_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_FIYATI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_KDV_HARICFY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_IND_FIYAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_ARA_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_IND_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOVIZ_BIRIMI" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BIRIM_CARPANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_CARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ORAN_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_OZEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_OZEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_ARATUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_TOPLAM_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_KDVLI_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_TOPLAM_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVZ_KDVLI_TUTAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MUH_KODU_GENEL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OZEL_KODU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EKBILGI_1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKBILGI_4" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_STOK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_PERSONEL" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAZ_PERS_BLKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_ORANI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BARKODU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VADE_GUNU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BLHZMKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BIRIMLER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="KPBDVZ" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ANA_STOKKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ISK_TUTAR_CARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_CARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_1_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_2_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_3_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_3_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_TUTAR_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_OZEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_OZEL_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ISK_SNTUTAR_STOK_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DEPO_ADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MIKTARI_TESLIM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTARI_IPTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MIKTARI_KALAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ASORTI_HRK" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ASORTI_MIKTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KDV_DURUMU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SIRA_NO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BLMRPEMIRKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PAZ_ISC_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_TUTARI_DVZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOVIZ_ALIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOVIZ_SATIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAZ_URUN_BF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KPB_FIYATI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SERINO_KULLAN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="STOK_ADI_YD" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="EK_DETAY_TUTARI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EK_DETAY_HESABI" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BLEKOZELLIK_KODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DVZ_FIYATI_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BLBURTKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="OFFLINE_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="STOK_BLOKE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BLITHALATKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GENEL_BLOB" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DEPOZITO_BLSTKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DEPOZITO_BLMASTERKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BLPAKETKODU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="OZELALANTANIM_17" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OZELALANTANIM_18" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>